---
- name: add docker group to host
  hosts: glusterfs
  sudo: True
  vars_files:
    - vars.yml

  tasks:
    - name: add docker group to host
      user: name={{ansible_ssh_user}} shell=/bin/bash groups=docker append=yes