---
- name: mount glusterfs volume
  hosts: swarm
  sudo: True
  vars_files:
    - vars.yml

  tasks:
    - name: Ensure Gluster mount directories exist.
      file: "path={{ item }} state=directory mode=0777"
      with_items:
        - "{{ gluster_mount_dir }}"

    - name: Ensure Gluster volume is mounted.
      sudo: True
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_tmpfs_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
