---
- name:  mount tmpfs as /tmp
  hosts: glusterfs
  sudo: yes

  vars_files:
    - vars.yml
    
  tasks:
    - name: mount tmpfs as /tmp
      mount: name=/tmp src='tmpfs' fstype=tmpfs state=mounted

    - name: Ensure Gluster brick directories exist.
      file: "path={{ item }} state=directory mode=0777"
      with_items:
        - "{{ gluster_brick_tmpfs_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_tmpfs_name }}"
        brick: "{{ gluster_brick_tmpfs_dir }}"
        stripes: 2
        replicas: 2
        cluster: "{{ groups.glusterfs | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true