---
- name: install docker
  hosts: swarm
  sudo: True

  tasks:
    - name: Install docker when Ubuntu
      sudo: True
      apt: pkg={{item}} update_cache=yes
      with_items:
        - apt-transport-https
        - ca-certificates
      when: ansible_distribution == "Ubuntu"

    - apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
      sudo: True

    - name: insert /etc/apt/sources.list.d/docker.list
      sudo: True
      lineinfile:
        create: yes
        dest: /etc/apt/sources.list.d/docker.list
        line: deb https://apt.dockerproject.org/repo ubuntu-wily main

    - name: Install docker when Ubuntu
      sudo: True
      apt: name=docker-engine update_cache=yes
      when: ansible_distribution == "Ubuntu"